### ISSUE TITLE
Add Phel syntax to Github

### ISSUE THREAD

**Issue by Chemaclass** [phel-lang/phel-lang#158]
I did some research, and I found that `github/linguist` has the syntax for the languages in Github. 

In their contributing file, you can find how to do this:  https://github.com/github/linguist/blob/master/CONTRIBUTING.md

The goal is to investigate and try this out.

**Comment by jenshaase** [comment]
> We try only to add languages once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.

Spread the world and make a lot of repositories :laughing:

**Comment by jenshaase** [comment]
I will close this ticket until Phel has enough usage.
