### ISSUE TITLE
Errored out expressions are not shown in repl history

### ISSUE THREAD

**Issue by aszenz** [phel-lang/phel-lang#205]
Using the up arrow in repl only traverses expressions that evaluated successfully, it's hard to fix an errored out expressions since it's not recorded in repl history

Example:
```
Type "exit" or press Ctrl-D to exit.
phel:1> (first [1 2 3])
1
phel:2> ( firsts [2])
Can not resolve symbol 'firsts'
in string:2

2| ( firsts [2])
     ^^^^^^
phel:3> (first [1 2 3]) # The up arrow shows the last successfully executed expression instead of the last written expression
```

**Comment by Chemaclass** [comment]
I did this intentionally. But now that you are reporting this issue, it makes me think that maybe it would be good as well to include in the repl-history all given inputs, and not only the successful ones 🤔 What do you think, @jenshaase?

**Comment by jenshaase** [comment]
@aszenz is correct. We should add these to the history!
