### ISSUE TITLE
New function: `php-indexed-array?`

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang#210]
I happened to have a need for this function in `phel-json` package.

```
# Taken from: https://stackoverflow.com/a/13522545
(defn- php-indexed-array? [arr]
    (cond
        (not (php-array? arr)) false
        (<= (count arr) 0) true
        true (= (keys arr) (range 0 (count arr)))))
```

> Check whether the input is an array whose keys are numeric, sequential, and zero-based.

Can/should this be included in Phel core?

Btw. `range` works differently than PHPs `range`. Is that a bug? eg. 

```
# php
(php/range 0 1) = <PHP-Array [0, 1]>

# phel
(range 0 1) = @[0]
```

**Comment by mabasic** [comment]
Also, issue  #211  is occurring here

```
(= (keys arr) (range 0 (count arr)))
```

**Comment by jenshaase** [comment]
Regarding `range`. It is correct that they differ. In Phel the end value is exclusiv. In PHP the end value is inclusive.

Tip: Instead of `(range 0 (count arr))` you can just write `(range (count arr))`

Regarding `php-indexed-array?`: You defined an empty as a non-indexed array. What is the idea behind that?

**Comment by mabasic** [comment]
Nice tip, thank you.

`php-indexed-array?` returns true only if these criteria are true:

- is php array
- keys are are numeric/integer, sequential and zero-based

It returns true for empty arrays.

**Comment by Chemaclass** [comment]
Instead of `php-indexed-array?`, what about `is-list?` or  `is-php-list?`?

**Comment by mabasic** [comment]
> Instead of `php-indexed-array?`, what about `is-list?` or `is-php-list?`?

If I was looking for something like this I would look for `indexed` and `associative`.

**Comment by jenshaase** [comment]
There is `indexed?` already. But it doesn't do the same. I will check if it makes sense to change it.

**Comment by Chemaclass** [comment]
I mentioned `is-list?` because there is coming a native PHP function in PHP 8.1 with that name. 
```php 
array_is_list(array $array): bool
``` 
Check it out -> https://wiki.php.net/rfc/is_list

**Comment by jenshaase** [comment]
I update the `indexed?` method to work like you proposed.
Additionally I added the `associative?` method as counterpart.

**Comment by mabasic** [comment]
@jenshaase Niceee! Going to update my code asap.
