### ISSUE TITLE
Allow function declarations as function symbols

### ISSUE THREAD

**Issue by Chemaclass** [phel-lang/phel-lang#228]
## Current behavior

Currently, the function name must a string

```
phel:1> ((set :a :b :c) :b)
Phel\Compiler\Emitter\Exceptions\CompiledCodeIsMalformedException: Function name must be a string
```

### Clojure example

In Clojure, you can use the `set` as a filter to know if an element exists or not in a given set.
https://clojuredocs.org/clojure.core/set

```clojure
((set :a :b :c) :b) => :b
((set :a :b :c) :d) => nil
```

## Acceptance Criteria

Implement this logic in Phel sets as well.

**Comment by jenshaase** [comment]
With release 0.3.0 this is working.
