### ISSUE TITLE
Adding examples section to the Phel website

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang#261]
I think that it would be great for adoption that people visiting the website see how Phel is being already used.

Here are some of my links. Others are welcome to add more stuff.

Links:

- https://github.com/mabasic/phel-json (Phel library for converting Phel data structures to and from JSON.)
- https://github.com/mabasic/mariobasic-n7 (Website built with Phel - source code)

**Comment by kloimhardt** [comment]
- https://github.com/kloimhardt/bb-web#phelphp-backend (small no-install ClojureScript web-app with Phel backend)

**Comment by jenshaase** [comment]
I added a 'In the wild' section to the website: https://phel-lang.org/documentation/in-the-wild/
