### ISSUE TITLE
Update data structures website documentation

### ISSUE THREAD

**Issue by Chemaclass** [phel-lang/phel-lang#268]
The `Persistent data structures` #244 was already merged in master. Now we need to update the website documentation. Especially these sections:

1. https://phel-lang.org/documentation/tuple/ -> now we have `list` (`(...)`) and `vector` (`[...]`) data structures
2. https://phel-lang.org/documentation/array-table-and-struct/ ->  instead of `table` we have a `hash-map` (e.g: `{:a 1 :b 2}`)

**Comment by jenshaase** [comment]
See PR #270

**Comment by Chemaclass** [comment]
Already merged https://github.com/phel-lang/phel-lang/pull/270
