### ISSUE TITLE
`for` returns an array instead of a vector

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang#275]
In the REPL:

```
phel:2> (for [x :range [0 3]] x)
@[0 1 2]
```

It should be:

```
[0 1 2]
```

I was trying to convert `mabasic/json` library to use the new data structures and then I noticed that `for` still returns an array which breaks my tests.

**Comment by jenshaase** [comment]
I created a pull request to solve the issue. After this is merged into master I will publish version 0.3.1.

**Comment by jenshaase** [comment]
Version 0.3.1 has been released.
