### ISSUE TITLE
PersistenVector "Index 2688 is not in interval [0, 2688)"  

### ISSUE THREAD

**Issue by Chemaclass** [phel-lang/phel-lang#302]
I am getting an interesting error when running this code: https://github.com/Chemaclass/phel-in-a-nutshell/blob/master/src/command/independent-script.phel

<img width="1766" alt="Screenshot 2021-06-02 at 22 37 37" src="https://user-images.githubusercontent.com/5256287/120548858-23cc6880-c3f3-11eb-9a2f-14c39801a8d6.png">

Is this an actual bug, or is there a problem in my phel code?

```clojure
(->> words
    (map php/strtolower)
    (filter |(not (get words-to-filter-out $))) ; <----- the problem must be in this line
    (frequencies)
    (pairs)
    (sort-by second)
    (take-last 5)
    (reverse)
    (apply println))
```

**Comment by jenshaase** [comment]
The problem happened on Vectors with the size of `length % 32 == 0`. The `RangeIterator` for this case had a bug that I fixed now.
