### ISSUE TITLE
Project description update of "In the Wild" docs

### ISSUE THREAD

**Issue by kloimhardt** [phel-lang/phel-lang#309]
I combined "bb-web" + "qlkit-todo-demo" into one improved repository. Please replace the respective two bullet points with one:

- [lisp-webscript-examples](https://github.com/kloimhardt/lisp-webscript-examples): Minimal reactive web-apps combining Phel+(no install)ClojureScript via GraphQl

link: https://github.com/kloimhardt/lisp-webscript-examples

**Comment by Chemaclass** [comment]
We moved recently the web to its own repository: https://github.com/phel-lang/phel-lang.org
Anyway, @JesusValera will work on it directly there. You don't need to re-create another issue or something.
Thanks for the update! 👌🏻

**Comment by Chemaclass** [comment]
The code fix was already done. @jenshaase will update the website in the next version 👌🏻
