### ISSUE TITLE
Error `Runtime` could not be loaded

### ISSUE THREAD

**Issue by JesusValera** [phel-lang/phel-lang#349]
I think since this PR https://github.com/phel-lang/phel-lang/pull/346, phel is not working anymore.
When you try to run the `composer install` command, the `Runtime` file is not generated and with the `phel test` command, everything explores 😄 

You can investigate just simply cloning a new project, installing the dependencies and executing `composer test-all` for example.

```bash
> ./phel test
Phel\Runtime\Exceptions\PhelRuntimeException: The Runtime could not be loaded from: /home/jesus/Desktop/phel-lang//vendor/PhelRuntime.php
in /home/jesus/Desktop/phel-lang/src/php/Runtime/Exceptions/PhelRuntimeException.php:13 (gen: /home/jesus/Desktop/phel-lang/src/php/Runtime/Exceptions/PhelRuntimeException.php:13)

#0 /home/jesus/Desktop/phel-lang/src/php/Runtime/RuntimeFactory.php(29): Phel\Runtime\Exceptions\PhelRuntimeException::couldNotBeLoadedFrom()
#1 /home/jesus/Desktop/phel-lang/src/php/Runtime/RuntimeFacade.php(16): Phel\Runtime\RuntimeFactory->getRuntime()
#2 /home/jesus/Desktop/phel-lang/src/php/Compiler/CompilerFactory.php(70): Phel\Runtime\RuntimeFacade->getRuntime()
```

**Comment by Chemaclass** [comment]
Did you try to generate the `PhelRuntime.php` file with `phel runtime` command?

**Comment by JesusValera** [comment]
Ok, I see!

I will close the issue then.
