### ISSUE TITLE
Can we add the Hacktoberfest tag to the repository?

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang#372]
https://hacktoberfest.digitalocean.com/resources/maintainers

**Comment by Chemaclass** [comment]
I am just wondering what's the point of adding that tag to the repo or PRs? I am not against it, I just didn't find a reason or a goal why to do that. Maybe you can add that information in the issue description?

**Comment by mabasic** [comment]
If you complete the challenge you can choose to plant a tree in your name or you can get a tshirt.

There are two ways to participate: as a maintainer or as a contributor.

Maintainer has to add the tag `hacktoberfest` to the repo or apply tag `hacktoberfest-accepted` to the PR and merge PRs.

Contributors have to submit PRs which get merged in this month.

**Comment by mabasic** [comment]
I've played for two years now and I have one tree planted 👍

**Comment by jenshaase** [comment]
I have heard of hacktoberfest, but only about the negative effects of it. I don't see any advantages of it yet. But if you want to do this challenge with Phel that I can add the tag to this repository.

**Comment by mabasic** [comment]
If you don't want, you can only mark my PR with that tag `hacktoberfest-accepted` so that I can get credited for it.

**Comment by Chemaclass** [comment]
I agree with @jenshaase. I don't see any problem adding the tag to some specific PR. Especially if you find some more typos or bug fixes, feel free to create a PR and we can add the label 🏷
