### ISSUE TITLE
TextExceptionPrinter::create method is not available anymore

### ISSUE THREAD

**Issue by jenshaase** [phel-lang/phel-lang#397]
In the test library the method `TextExceptionPrinter::create` is called:

https://github.com/phel-lang/phel-lang/blob/6fb71e33c8e8b114e38cb64f166092bfb1e166da/src/phel/test.phel#L217

 This method isn't available anymore.

I would recommend to make it accessible from the CommandFacade

**Comment by Chemaclass** [comment]
There is no `TextExceptionPrinter::create()` anymore, that's right, but how is this even working? How is it possible that I don't see any PHP error when I run a failing test? 😮 How could you reproduce this bug, @jenshaase?
<img width="784" alt="Screenshot 2021-12-11 at 13 47 38" src="https://user-images.githubusercontent.com/5256287/145677016-2a003b4e-4f92-4aff-967b-60d509c9c048.png">

**Comment by jenshaase** [comment]
The test must not just fail. It must throw an exception.
