### ISSUE TITLE
Add a `fn?` function

### ISSUE THREAD

**Issue by jenshaase** [phel-lang/phel-lang#398]
A new `fn?` method should be added.

Possible implementation:
```
(defn fn? [x] (php/instanceof x FnInterface))
```

Additionally the `type` method should be updated to return `:fn` if a function is provided.

**Comment by JesusValera** [comment]
I am not sure if I understood correctly.
The new `fn?` function will return the `fn` if it already exists?

**Comment by Chemaclass** [comment]
@JesusValera, the goal is to be able to know if a variable is a function. 
`fn?` will be the function that receives an argument `x`, and `x` is the variable that you want to check if it's a function.

**Comment by Chemaclass** [comment]
@jenshaase, I see we have already: `(php/is_callable x) :function` (see: `core.phel:597`). What would be the difference between `function?` and `fn?`? Well, the clear diff is that one check for `is_callable()` and the other one implements `FnInterface`, but does it make sense to have both? I think the requirements aren't 100% clear right now 🤔

**Comment by jenshaase** [comment]
I think I overlooked this function yesterday. Then it is not required anymore. Using is_callable is even a better implementation. I will close this ticket now.

**Comment by Chemaclass** [comment]
Lucky @JesusValera, that was fast... 😂
