### ISSUE TITLE
Ignore the MixedReturnStatement errors from psalm level 1

### ISSUE THREAD

**Issue by Chemaclass** [phel-lang/phel-lang#464]
Currently, if we set psalm level 1 we get lot of these errors:
```php
ERROR: MixedReturnStatement - src/php/Run/RunFactory.php:97:16 - Could not infer a return type
return $this->getProvidedDependency(RunDependencyProvider::FACADE_COMMAND);
```

The reason is because `getProvidedDependency()` returns a `mixed`, and this is OK (and code from Gacela).
```php
/**
 * @return mixed
 */
protected function getProvidedDependency(string $key)
{
    return $this->getContainer()->get($key);
}
```

The solution for this could be defining a rule somehow in the `psalm.xml` config file to ignore these errors.

> Interesting link: https://psalm.dev/docs/running_psalm/dealing_with_code_issues/

**Comment by jenshaase** [comment]
Alternative solution could be to set the type:

```php
private function getCompilerFacade(): CompilerFacadeInterface
{
  /** @var CompilerFacadeInterface $result */
  $result = $this->getProvidedDependency(RunDependencyProvider::FACADE_COMPILER);
  return $result;
}
```
