### ISSUE TITLE
Create int function

### ISSUE THREAD

**Issue by JesusValera** [phel-lang/phel-lang#540]
Currently, we have the `int?` function that checks if the current value is `int` value or not (returns a bool).
But we don't have an `int` function that casts a variable to an `int`.
I propose a new set of functions to cast as follows:
```lisp
(int "42") # output: 42 (integer)
```
Same for bool, float, string.

Does it make sense to add also for vector, list, map & set?

---

Additionally, maybe we could also add a super cast function with a match that can cast a value to another type, maybe something like:

```lisp
(cast int "42") # output: 42 (integer)
(cast string 3.5) # output "3.5" (string)
```

What do you think @jenshaase @Chemaclass ?

**Comment by Chemaclass** [comment]
You can do this using native PHP: `(php/intval i)` (eg [I used it here](https://github.com/Chemaclass/phel-snake/blob/master/src/logic.phel#L74)), however, I think it might be handy to have this as an internal native phel function `(int i)`. What do you think, @jenshaase?

**Comment by Chemaclass** [comment]
I created a PR with this idea https://github.com/phel-lang/phel-lang/pull/554 so I will close this issue and we can follow the conversation in the PR instead.
