### ISSUE TITLE
php/apush and php/aset not working as expected

### ISSUE THREAD

**Issue by cgrabenstein** [phel-lang/phel-lang#578]
| Q                   | A               |
|---------------------|-----------------|
| Phel version        | 0.9.0           |
| PHP version         | 8.1.15           |

#### Summary

`php/apush` and `php/aset` not working as expected.

#### Current behavior

When using `php/apush` or `php/aset` I expect to get the updated array returned. Instead I only get the newly added item. I have no possibility to access the updated array. Or at least I could not find any way to do so.

#### How to reproduce

```
phel:1> (def arr (php/array 1 2 3))
1
phel:2> arr
<PHP-Array [1, 2, 3]>
phel:3> (type arr)
:php/array
phel:4> (php/apush arr 4)
4
phel:5> arr
<PHP-Array [1, 2, 3]>
phel:6> (def new-arr (php/apush arr 4))
1
phel:7> new-arr
4
phel:8> (type new-arr)
:int
```

#### Expected behavior

I would expect that `new-arr` in the example above holds an array with the values 1, 2, 3 and 4.

**Comment by Chemaclass** [comment]
Fixed here https://github.com/phel-lang/phel-lang/pull/579
