### ISSUE TITLE
Not able to execute generated php code

### ISSUE THREAD

**Issue by bentxt** [phel-lang/phel-lang#589]
According to the scaffolding repo it should be possible to make direct use of php code:

https://github.com/phel-lang/phel-scaffolding/blob/master/example/using-exported-phel-function.php

This doesnt work, and its also not possible to run simply `php hello.php` in the `out/hello-world/` directory. There are always errors from the phel runtime not able to find some classes.

Could you give me a very simple example on how to run the generated php code as direct and simple as possible?

Thank you very much.

**Comment by bentxt** [comment]
In the scaffolding example I get the following error:
```
> php using-exported-phel-function.php
Error: Class "PhelGenerated\PhelScaffolding\Modules\AdderModule" not found
in /Users/ben/hack/phel/phel-scaffolding.git/out/using-exported-phel-function.php:12 (gen: /Users/ben/hack/phel/phel-scaffolding.git/out/using-exported-phel-function.php:12)
```

**Comment by Chemaclass** [comment]
@bentxt thanks for your feedback! Have you run the `vendor/bin/phel export` command?
Can you try again using the [cli-skeleton](https://github.com/phel-lang/cli-skeleton)? 
1.- fork or clone or use-template 
2.- composer install # to install all dependencies
3.- vendor/bin/phel export
4.- php example/using-exported-phel-function.php

<img width="888" alt="Screenshot 2023-04-01 at 18 43 12" src="https://user-images.githubusercontent.com/5256287/229303625-31f49a79-7861-4585-92ac-cd93c511578b.png">

>**Note**: I updated the docs using the latest release 0.10; using the new fluent config in the `phel-config.php`

**Comment by bentxt** [comment]
Hi, 
Thanks alot for your help. I have still have to make a few remarks

While the `export` command works like to describe, I still get the error with the `build` command. I'm confused why it doesnt work and since the problem with `build` is not really addresse here, I will make a new ticket. Hope thats ok.
