### ISSUE TITLE
Docs: Documentation for Library-Developers would be great

### ISSUE THREAD

**Issue by mabasic** [phel-lang/phel-lang#59]
We need to document this: #52 

It should cover:
- private/public functions/values
- namespaces
- composer phel configuration
- testing

**Comment by mabasic** [comment]
@jenshaase I would like to work on this issue too. Once you have implemented a testing library I can work on this?

**Comment by mabasic** [comment]
Totally forgot about this... Going to give it a try

**Comment by jenshaase** [comment]
No problem. Take your time.

**Comment by mabasic** [comment]
I am thinking of creating a library for json encoding and decoding as we talked on gitter and publishing it on packagist. It should be pretty simple to write documentation for library developers using this as an example.

If this does end up in the core phel, I could archive the repository so that it will serve as an example.

**Comment by mabasic** [comment]
**Update**: I've managed to produce working code for encoding Phel data structures (for now just array, table) to JSON and it works. 

My next step is to put the code (library) on GitHub and write/use tests to cover all data structures before publishing it on packagist. I would be honored if you all could review the code before I publish it and provide me with hints/tips/suggestions so that I can improve the code and learn more. Thank you.

**Comment by mabasic** [comment]
I have created a repo and pushed code to it for the json wrapper library: https://github.com/mabasic/phel-json Please take a look and tell me your thoughts. It is in an early stage and missing a lot of things, but seems promising.

**Comment by mabasic** [comment]
I am waiting for #165 to be resolved in order to improve my json wrapper library around which I will write the documentation for library developers.

**Comment by jenshaase** [comment]
I have #165 on my list. By the way, what is the best way to give you feedback on your lib?

**Comment by mabasic** [comment]
Issues, gitter, email. Whatever is easier to you.

**Comment by Chemaclass** [comment]
What about including this `encode-json` inside the official phel repo? This is related with the topic that we talked on gitter https://gitter.im/phel-lang/community?at=6000524003529b296bed1700 

I think it would be better for phel if we have a `json.phel` module which have the `encode` and `decode` functions, so everyone can `:require` them and use them out of the box, because they are really specific on "phel types and json from PHP". With a good test suite, I see only benefits.

**Comment by mabasic** [comment]
Agreed.

My idea for creating a separate repository, was for it to serve as an example library for library-developers documentation. My intention was to publish it, archive it and then submit a PR to Phel to add the library to the core.

**Comment by Chemaclass** [comment]
What do you think @mabasic and @jenshaase about including the `json.phel` (and the tests, for sure) inside the `src/phel/` directory in the **phel-lang** repo? I think it would be great to have such thing inside the project, because it's a really common thing to have in a language. Also, it wouldn't affect the load-speed for the end user, because it will be compiled only if it's required.
Now reading the comment from @mabasic from 14 January, I think this was the original idea. I wanted to revisit this topic again :)

**Comment by mabasic** [comment]
Agreed. That was always my intention. I still need to write the documentation for creating a phel package.

**Comment by jenshaase** [comment]
Yes we can merge them. Can somebody create a Pull Request?

**Comment by mabasic** [comment]
> Yes we can merge them. Can somebody create a Pull Request?

I'll create a PR because there is one thing that needs changing in the library to be useful. I discovered it while building my website.

**Comment by mabasic** [comment]
I have created a PR to merge phel-json library to Phel. I will try to do this task promptly.

**Comment by Chemaclass** [comment]
Is this issue still relevant, @mabasic, or can we close it?

**Comment by mabasic** [comment]
> Is this issue still relevant, @mabasic, or can we close it?

Yes, it is still relevant. I haven't done anything about this lately, but it is on my mind. I'll do this once I update my website to the latest version.

**Comment by JesusValera** [comment]
Hello @mabasic, we are cleaning up the issues as much as possible.
Could you take a look at this one? If you cannot soonish, it is fine, we can close it and maybe open it again in the future, what do you think? 😄

**Comment by mabasic** [comment]
I will do it tonight If I don't fall asleep, or I will probably never do it and it that case you can close it tomorrow :)

**Comment by JesusValera** [comment]
@mabasic nice.
In case you start with that, it doesn't have to be 100% ready, you can do a small prototype, and we can work on this in follow-up iterations 👌🏼

**Comment by mabasic** [comment]
Took me three years to write this xD It has some rough edges, but I'm sure that library authors will find helpful information here.
