### ISSUE TITLE
Some functions are missing in the API

### ISSUE THREAD

**Issue by JesusValeraDev** [phel-lang/phel-lang#595]
## 📚 Description

If we try to search functions like `doc`, `use` or `require` (described in the [REPL section](https://phel-lang.org/documentation/repl/)), we don't get results.
It would be nice to add them (also check we are not missing any other function from the documentation) in the `API` section.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/6381924/233112925-104a9962-5eb2-48b8-92cd-8105a07b3a5a.png">

**Comment by Chemaclass** [comment]
These repl helpers are loaded on the fly when running the repl, and the api page right now is just reading the functions from `src/phel`. Maybe it would be interesting to add these three helpers in the API page as well, and add in the docstring something saying "only accesible from the repl"

**Comment by jenshaase** [comment]
The special repl functions are the `phel\repl` namespace. We can just add the namespace here: https://github.com/phel-lang/phel-lang.org/blob/master/build/src/php/FileGenerator/Config.php and they will be part of the documentation.
