### ISSUE TITLE
Add hacktoberfest topic for this month

### ISSUE THREAD

**Issue by lhsazevedo** [phel-lang/phel-lang#622]
I noticed some issues marked as good first issues and they are perfect for beginners and newcomers looking for simple tasks to pickup:
- #478
- #479
- #480
- #481

Hacktoberfest is an annual event by Digital Ocean that aims to promote contributions to open source projects. You can attract more first time contributors by adding the `hacktoberfest` topic to the repo, and you don't need to worry about adding the `hacktoberfest-accepted` tag to all merged PRs.

_Disclaimer: I am also a participant in the event and have made contributions to this project during this month._

**Comment by Chemaclass** [comment]
Hi, @lhsazevedo! Thanks for reaching out. I added the `hacktoberfest` to the repo for this month. 
Feel free to work on any of those issues.

**Comment by lhsazevedo** [comment]
Thank you! We'll try to make in-person event to help beginners work on those
