### ISSUE TITLE
Update Documentation for true precompiled web apps

### ISSUE THREAD

**Issue by bentxt** [phel-lang/phel-lang#669]
I have Phel on the radar since the beginning. The reason I could not use it was simply I never was able to make the precompilation (to PHP files) work, the way I wanted, which is by removing all phel files.

Right now in the tutorial the 'src' directory is still used and I guess the boot.phel is still interpreted.

If you update the index.php the tutorial works enterily with precompiled files:
```
<?php

declare(strict_types=1);

use Phel\Phel;

$projectRootDir = dirname(__DIR__);
require $projectRootDir . '/vendor/autoload.php';

$appFile = $projectRootDir . "/out/hello_world/boot.php";

if (file_exists($appFile)) {
    require_once $projectRootDir . "/out/hello_world/boot.php";
} else {
    Phel::run($projectRootDir, 'hello-world\boot');
}
```

**Comment by Chemaclass** [comment]
Yes, it's possible to build the project into pure raw PHP files, and then execute the PHP files natively.
Check this project as reference: https://github.com/Chemaclass/phel-snake 
> There, for example, you can build the game with `vendor/bin/phel build`, this will generate a file in `out/play.php` (defined in the `phel-config.php ::setOut()`), and then you will be able to execute it with `php out/play.php`

**Comment by bentxt** [comment]
> Yes, it's possible to build the project into pure raw PHP files, and then execute the PHP files natively. Check this project as reference: https://github.com/Chemaclass/phel-snake

Thanks for the link


> Check: https://phel-lang.org/documentation/configuration/
Yes thanks again for this link, at one point I was indeed interested in one of those config directives, but the search yielded no results, therefore I assumend it didn't work. Now I see it is the search function which doesn't seem to search in the code fields.


> Is this helping, or do you mean other thing?
both it is helping, but I thought it would be cool to have the `index.php` in updated, for a fully functional web example

**Comment by Chemaclass** [comment]
@bentxt thanks for your feedback!
I already updated the index.php with your suggestion. Check it out: https://github.com/phel-lang/web-skeleton/blob/main/public/index.php

You can also use the composer scripts to make it simpler the DX
- `composer run:dev`: removes the build out directory, and start the local server; it will compile the phel project on the fly for every refresh of the page, so you can see the changes of your phel files for dev purposes
- `composer run:prod`: run `phel build`, and start the local server using the result build; it wont compile for every refresh, instead, it will use the native PHP files, so no performance lost :)
