### ISSUE TITLE
The `interleave` function in Phel-lang behaves differently from its counterpart in Clojure when encountering nil values.

### ISSUE THREAD

**Issue by smeghead** [phel-lang/phel-lang#681]
| Q                   | A               |
|---------------------|-----------------|
| Phel version        | 0.12.0          |
| PHP version         | 8.1.13          |

#### Summary

The `interleave` function in Phel-lang behaves differently from its counterpart in Clojure when encountering nil values.

#### Current behavior

In Phel-lang, when using the `interleave` function with two collections where one contains nil values, the nil values are ignored in the resulting sequence. This differs from Clojure, where nil values are included in the resulting sequence.

#### How to reproduce

```phel
(interleave ["s1" "s2"] [1 nil])
=> [s1 1]
```

The return value of the `interleave` function does not include `"s2" nil`.

#### Expected behavior

I expect the return value of the `interleave` function to contain `"s2" nil`

Phel-lang:

```phel
(interleave ["s1" "s2"] [1 nil])
=> [s1 1 s2 nil]
```

The behavior is the same as clojure's `interleave` function.

Clojure:

```clojure
(interleave ["s1" "s2"] [1 nil])
=> (s1 1 s2 nil)
```

**Comment by Chemaclass** [comment]
The main issue with this is that we are using nil as undefined as well, so it's treating both as the same. Do you have some hint/idea how could we solve this, @jenshaase? For example, differentiating `nil` vs `:undefined` or somthing like that?

**Comment by Chemaclass** [comment]
I am trying to reproduce your code, @smeghead, but I get this error. Can you give me a more more context, or share a link to a gist or your project to take a better look 👀 

![Screenshot 2024-04-16 at 16 38 15](https://github.com/phel-lang/phel-lang/assets/5256287/f40bc4e3-c6ea-4bb0-9570-61afafb94955)

**Comment by smeghead** [comment]
@Chemaclass 
my `interleave-local` function is here.

https://github.com/smeghead/phel-str/blob/main/src/test.phel#L3

I'm trying to define a macro with `defmacro` and trying to use the `interleave` function.
And to avoid the problem I defined a temporary `interleave-local` function.
`interleave-local` is woks.

Does the behavior change depending on the definition position of the `max` function?...

**Comment by Chemaclass** [comment]
@smeghead PR open and ready for review with your suggestion: https://github.com/phel-lang/phel-lang/pull/682

**Comment by smeghead** [comment]
@Chemaclass 
Thank you.
Using the modified `interleave` function in phel 0.13.0, I am able to define the macro I wanted.
I have confirmed that it works without any problems.
https://github.com/smeghead/phel-str/blob/main/src/test.phel#L9
