### ISSUE TITLE
Should phel maps be guaranteed to be in order?

### ISSUE THREAD

**Issue by smeghead** [phel-lang/phel-lang#734]
| Q                   | A               |
|---------------------|-----------------|
| Phel version        | 0.15           |
| PHP version         | 8.2.21           |

#### Summary

Should phel maps be guaranteed to be in order?
PHP's associative arrays are guaranteed to be in map order, but many other languages do not guarantee map order.

#### Current behavior

When a PHP array with more than 16 elements is converted to a map with `php-array-to-map`, the 16th element of the array is displayed at the top.

#### How to reproduce

```clojure
phel:1> (php-array-to-map (php/array
                    "str-1"
                    "str-2"
                    "str-3"
                    "str-4"
                    "str-5"
                    "str-6"
                    "str-7"
                    "str-8"
                    "str-9"
                    "str-10"
                    "str-11"
                    "str-12"
                    "str-13"
                    "str-14"
                    "str-15"
                    "str-16"
                    "str-17"))
{16 str-17 0 str-1 1 str-2 2 str-3 3 str-4 4 str-5 5 str-6 6 str-7 7 str-8 8 str-9 9 str-10 10 str-11 11 str-12 12 str-13 13 str-14 14 str-15 15 str-16}
```

`16 str-17` is represented at the top.

#### Expected behavior

The phel map is not a bug if the policy is not to guarantee order.
Is this the intended behavior?

**Comment by Chemaclass** [comment]
The order of a hash-map is not guaranteed. While the order may be preserved in some cases, it is not a reliable aspect of their functionality and should not be relied upon. If a consistent order is required, use a vector or a list.

Another question would be: do we want to keep it "backward compatible" with PHP and guarantee the order? 
That's another question. What do you think, @jenshaase?

**Comment by jenshaase** [comment]
I would ask the question what is the value of ordered maps? I cannot think of any use case in my professional career where I would like to have this feature.

Additionally, there is another important point. PHP array keys can only be of type string or int. In Phel any key type is possible (e.g. keywords). This makes ordering very hard or impossible.
