### ISSUE TITLE
Add option to disable Phel's error handling

### ISSUE THREAD

**Issue by jasalt** [phel-lang/phel-lang#769]
Phel uses PHP `set_error_handler` in [ExceptionHandler.php](https://github.com/phel-lang/phel-lang/blob/efb8f3a02e9d852da5b4032b9c33cd9eecc6f8ff/src/php/Command/Infrastructure/ExceptionHandler.php#L60) which overrides any existing error handling configuration. This leads to problems eg. when Phel script is loaded as part of WordPress plugin.

For more context, WordPress has it's [WP_Error class](https://github.com/WordPress/WordPress/blob/ea472597956e31c9aa4421300b13ae481679df07/wp-includes/class-wp-error.php#L19) as plus also some more [ad-hoc calls to set_error_handler](https://github.com/search?q=repo%3AWordPress%2FWordPress+set_error_handler&type=code) and so on.

A production WordPress site often sets following in `wp-config.php`, hiding all specific error output from site viewer, which is not respected by the Phel configuration as Phel takes over and writes (all) errors on display:

```
define('WP_DEBUG', false);
define('WP_DEBUG_DISPLAY', false);
define('WP_DEBUG_LOG', false);
define('SCRIPT_DEBUG', false);
```

On log file side, Phel logs errors in it's own log file and the error information does not flow into regular WordPress site's error log, only a reference to Phel plugin dir is written on WP `debug.log` during errors including phel plugin errors and errors from anywhere else:

```
[15-Nov-2024 11:00:48 UTC] /data/wordpress/htdocs/wp-content/plugins/phel-wp-plugin/
[15-Nov-2024 11:00:49 UTC] /data/wordpress/htdocs/wp-content/plugins/phel-wp-plugin/
[15-Nov-2024 11:00:49 UTC] /data/wordpress/htdocs/wp-content/plugins/phel-wp-plugin/
```

Phel's log writing should be maybe skipped altogether so it would be handled "on upper level" WP side.

Additionally setting error reporting levels to eg. skip only deprecation notices with `error_reporting(E_ALL ^ E_DEPRECATED);` does not work, maybe it could be a useful thing to allow customizing that in Phel error handler in general, but that could be it's own issue.

I was looking if there was a self evident way to make this possible but would like to have more official opinion on how to achieve this in best way, I'm just getting familiar with Phel code and PHP error handling in general.

Some testing in `Phel\Command\Infrastructure` ns where I was able to disable printing errors to display, while error log file problem remained:

```
private function registerCustomErrorHandler(): void
    {
        return;  //   <-- Added return here to disable Phel's error printing to display
        set_error_handler(function (
            int $errno,
            string $errstr,
            string $errfile = '',
            int $errline = 0,
            array $errcontext = [],
        ): bool {
            $errorNumber = error_reporting();
            $text = sprintf(
                "[%s] Error %s(%d) found!\nmessage: \"%s\"\nfile: %s:%d\ncontext: %s",
                date(DATE_ATOM),
                self::ERROR_TYPES[$errorNumber] ?? 'Unknown',
                $errorNumber,
                $errstr,
                $errfile,
                $errline,
                json_encode([...$errcontext, 'errno' => $errno], JSON_THROW_ON_ERROR),
            );

            if (self::$previousTextError !== $text) {
                $this->exceptionPrinter->printError($text);
            } else {
                $this->exceptionPrinter->printError('and again');
            }

            self::$previousTextError = $text;
            return true;
        }, E_ALL );
    }

```

Some current questions:

1) Is there a better location for disabling Phel's display error printing than above?
2) How to skip setting Phel error log file setting, so that logging setup "on upper level" keeps working? Looking into this next..
3) Where and how should this be set by user ideally?
   - new configuration option in `phel-config.php`
   - new parameter in `Phel::run` (more flexible?)
   - intelligently decide on runtime (doubt if possible)
   - something else..

**Comment by jasalt** [comment]
Seems there's something more complicated going on with WP error logging behavior in that it's error log keeps getting filled with log entries such as:
```
[15-Nov-2024 11:00:49 UTC] /data/wordpress/htdocs/wp-content/plugins/phel-wp-plugin/
```
.. coming from every page load, eventhough `Phel::run` hasn't run on that particular url, just by having Phel plugin "activated". Some other weird behavior too, I'll try to make sense that separately and return to clarify this feature request..

**Comment by Chemaclass** [comment]
I found that the `ExceptionHandler` is not really used/working as expected. Instead, the rendering on the terminal-output+error-log is from this one [RunCommand](https://github.com/phel-lang/phel-lang/blob/main/src/php/Run/Infrastructure/Command/RunCommand.php#L66), also see: [writeStackTrace](https://github.com/phel-lang/phel-lang/blob/main/src/php/Command/Application/CommandExceptionWriter.php#L23).

I am working on removing the dead-code to clarify how this gets used. I think we could remove using `set_exception_handler` and `set_error_handler` at all - aka, removing the [ExceptionHandler](https://github.com/phel-lang/phel-lang/blob/main/src/php/Command/Infrastructure/ExceptionHandler.php) class. At least this is my assumption for now, I will work towards this direction, let see if this make sense afterwards 🤔 

Is this new information helping you somehow, @jasalt ?

**Comment by Chemaclass** [comment]
@jasalt I merged the https://github.com/phel-lang/phel-lang/pull/770 to main and created a [PR](https://github.com/jasalt/phel-wp-plugin/pull/2) for your project using main to simplify the integration experience 🏗️

**Comment by Chemaclass** [comment]
Closing this issue, as phel does not have custom `set_error_handler` or `set_exception_handler` after https://github.com/phel-lang/phel-lang/pull/770

**Comment by jasalt** [comment]
Thank's, I'll see the situation with this through again in a bit. No wonder I had bit hard time reasoning how this worked, hehe.
