### ISSUE TITLE
Temporary files are not being removed with `->setKeepGeneratedTempFiles(false)` in some occasions

### ISSUE THREAD

**Issue by jasalt** [phel-lang/phel-lang#772]
- PHP version | 8.2.25
- Phel version | v0.15.3 dev-main (cbdd18644634384aba6fae3503b82678e5155b33)

#### Summary

Noted in https://github.com/jasalt/phel-wp-plugin/issues/12 that `phel-config.php` config option `->setKeepGeneratedTempFiles(false)` does not seem to have effect and amount of temporary files in `/tmp/` keeps growing on every request when running Phel as part of WordPress plugin.

#### How to reproduce

See linked issue.

#### Expected behavior

Amount of old temporary files in `/tmp/` should not grow, as when running Phel directly from command line.

**Comment by smeghead** [comment]
I did some research on this.

Phel can be executed via the `bin/phel` command or by calling the `Phel\Phel::run()` method from within a PHP script.

Deleting `/tmp/__phel*` seems to be done in `Phel\Console\Infrastructure\ConsoleBootstrap::run()` after running via the `bin/phel` command.

On the other hand, if you call the `Phel\Phel::run()` method, it may be that the process of deleting `/tmp/__phel*` is not performed.

**Comment by Chemaclass** [comment]
@smeghead you are 100% right! Here is the fix https://github.com/phel-lang/phel-lang/pull/774
