### ISSUE TITLE
Lots of Deprecated messages

### ISSUE THREAD

**Issue by bentxt** [phel-lang/phel-lang#781]
## Error/Question

I get a lot of these Deprecated messages:

```
Deprecated: Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $input as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
PHP Deprecated:  Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $output as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
```

## Specs
```
$ ./vendor/bin/phel --version
Phel v0.15.2
[I] ben@moonraker ~/B/p/example-app> rm -rf out/^C
[I] ben@moonraker ~/B/p/example-app> ./vendor/bin/phel --version

$ php --version
PHP 8.4.1 (cli) (built: Nov 20 2024 09:48:35) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies

$ composer --version
Composer version 2.8.3 2024-11-17 13:13:04
PHP version 8.4.1 (/usr/local/Cellar/php/8.4.1_1/bin/php)
Run the "diagnose" command to get more detailed diagnostics output.
```

**Comment by Chemaclass** [comment]
@bentxt , can you share the entire list/output with all different messages? or is just these two lines? 
```
Deprecated: Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $input as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
PHP Deprecated:  Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $output as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
```
In such case, this might fix it https://github.com/phel-lang/phel-lang/pull/783

**Comment by Chemaclass** [comment]
The thing is that PHP 8.4 is very fresh, and there are still some things to adapt to make it work 100%
In the meanwhile, if you want to give it a try to phel, you can use PHP 8.3 which is tested and working fine.

However, I appreciate if you help me finding these "broken UX" use-cases to fix for PHP 8.4, this will definitely help us to make the upgrade faster :)

**Comment by bentxt** [comment]
example-app> ./vendor/bin/phel build
PHP Deprecated:  Gacela\Framework\Gacela::bootstrap(): Implicitly marking parameter $configFn as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Gacela.php on line 39

Deprecated: Gacela\Framework\Gacela::bootstrap(): Implicitly marking parameter $configFn as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Gacela.php on line 39
PHP Deprecated:  Phel\Phel::run(): Implicitly marking parameter $argv as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Phel.php on line 29

Deprecated: Phel\Phel::run(): Implicitly marking parameter $argv as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Phel.php on line 29
PHP Deprecated:  Gacela\Framework\Bootstrap\GacelaConfig::enableFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 190

Deprecated: Gacela\Framework\Bootstrap\GacelaConfig::enableFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 190
PHP Deprecated:  Gacela\Framework\Bootstrap\GacelaConfig::setFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 199

Deprecated: Gacela\Framework\Bootstrap\GacelaConfig::setFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 199
PHP Deprecated:  Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $input as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21

Deprecated: Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $input as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
PHP Deprecated:  Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $output as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21

Deprecated: Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $output as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
PHP Deprecated:  Constant Phel\Command\Infrastructure\E_STRICT is deprecated in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Command/Infrastructure/ExceptionHandler.php on line 28

Deprecated: Constant Phel\Command\Infrastructure\E_STRICT is deprecated in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Command/Infrastructure/ExceptionHandler.php on line 28
[2024-12-13T12:53:51+00:00] Error E_ALL(30719) found!
message: "Phel\Lang\Keyword::__invoke(): Implicitly marking parameter $default as nullable is deprecated, the explicit nullable type must be used instead"
file: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Lang/Keyword.php:27
context: {"errno":8192}
#0 | Namespace: phel\core
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/core.phel
Target: ~/Builds/phel/example-app/out/phel/core.php

#1 | Namespace: phel\repl
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/repl.phel
Target: ~/Builds/phel/example-app/out/phel/repl.php

#2 | Namespace: user
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Run/Domain/Repl/startup.phel
Target: ~/Builds/phel/example-app/out/user.php

#3 | Namespace: phel\test
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/test.phel
Target: ~/Builds/phel/example-app/out/phel/test.php

#4 | Namespace: phel\http
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/http.phel
Target: ~/Builds/phel/example-app/out/phel/http.php

#5 | Namespace: phel\json
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/json.phel
Target: ~/Builds/phel/example-app/out/phel/json.php

#6 | Namespace: phel\str
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/str.phel
Target: ~/Builds/phel/example-app/out/phel/str.php

#7 | Namespace: phel\html
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/html.phel
Target: ~/Builds/phel/example-app/out/phel/html.php

#8 | Namespace: cli-skeleton\modules\adder-module
Source: ~/Builds/phel/example-app/src/modules/adder-module.phel
Target: ~/Builds/phel/example-app/out/cli_skeleton/modules/adder_module.php

#9 | Namespace: cli-skeleton\main
Source: ~/Builds/phel/example-app/src/main.phel
Target: ~/Builds/phel/example-app/out/cli_skeleton/main.php

Time: 00:00.852, Memory: 30.00 MB

**Comment by bentxt** [comment]
> @bentxt , can you share the entire list/output with all different messages? or is just these two lines?

example-app> ./vendor/bin/phel build
PHP Deprecated:  Gacela\Framework\Gacela::bootstrap(): Implicitly marking parameter $configFn as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Gacela.php on line 39

Deprecated: Gacela\Framework\Gacela::bootstrap(): Implicitly marking parameter $configFn as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Gacela.php on line 39
PHP Deprecated:  Phel\Phel::run(): Implicitly marking parameter $argv as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Phel.php on line 29

Deprecated: Phel\Phel::run(): Implicitly marking parameter $argv as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Phel.php on line 29
PHP Deprecated:  Gacela\Framework\Bootstrap\GacelaConfig::enableFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 190

Deprecated: Gacela\Framework\Bootstrap\GacelaConfig::enableFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 190
PHP Deprecated:  Gacela\Framework\Bootstrap\GacelaConfig::setFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 199

Deprecated: Gacela\Framework\Bootstrap\GacelaConfig::setFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 199
PHP Deprecated:  Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $input as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21

Deprecated: Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $input as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
PHP Deprecated:  Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $output as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21

Deprecated: Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $output as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
PHP Deprecated:  Constant Phel\Command\Infrastructure\E_STRICT is deprecated in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Command/Infrastructure/ExceptionHandler.php on line 28

Deprecated: Constant Phel\Command\Infrastructure\E_STRICT is deprecated in ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Command/Infrastructure/ExceptionHandler.php on line 28
[2024-12-13T12:53:51+00:00] Error E_ALL(30719) found!
message: "Phel\Lang\Keyword::__invoke(): Implicitly marking parameter $default as nullable is deprecated, the explicit nullable type must be used instead"
file: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Lang/Keyword.php:27
context: {"errno":8192}
#0 | Namespace: phel\core
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/core.phel
Target: ~/Builds/phel/example-app/out/phel/core.php

#1 | Namespace: phel\repl
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/repl.phel
Target: ~/Builds/phel/example-app/out/phel/repl.php

#2 | Namespace: user
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/php/Run/Domain/Repl/startup.phel
Target: ~/Builds/phel/example-app/out/user.php

#3 | Namespace: phel\test
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/test.phel
Target: ~/Builds/phel/example-app/out/phel/test.php

#4 | Namespace: phel\http
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/http.phel
Target: ~/Builds/phel/example-app/out/phel/http.php

#5 | Namespace: phel\json
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/json.phel
Target: ~/Builds/phel/example-app/out/phel/json.php

#6 | Namespace: phel\str
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/str.phel
Target: ~/Builds/phel/example-app/out/phel/str.php

#7 | Namespace: phel\html
Source: ~/Builds/phel/example-app/vendor/phel-lang/phel-lang/src/phel/html.phel
Target: ~/Builds/phel/example-app/out/phel/html.php

#8 | Namespace: cli-skeleton\modules\adder-module
Source: ~/Builds/phel/example-app/src/modules/adder-module.phel
Target: ~/Builds/phel/example-app/out/cli_skeleton/modules/adder_module.php

#9 | Namespace: cli-skeleton\main
Source: ~/Builds/phel/example-app/src/main.phel
Target: ~/Builds/phel/example-app/out/cli_skeleton/main.php

Time: 00:00.852, Memory: 30.00 MB

**Comment by bentxt** [comment]
> In such case, this might fix it #783

No unfortunately I think it doesnt fix it. I tried it with the fresh git clone 

```
./bin/phel --version
PHP Deprecated:  Gacela\Framework\Gacela::bootstrap(): Implicitly marking parameter $configFn as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/vendor/gacela-project/gacela/src/Framework/Gacela.php on line 39

Deprecated: Gacela\Framework\Gacela::bootstrap(): Implicitly marking parameter $configFn as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/vendor/gacela-project/gacela/src/Framework/Gacela.php on line 39
PHP Deprecated:  Phel\Phel::run(): Implicitly marking parameter $argv as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/src/php/Phel.php on line 36

Deprecated: Phel\Phel::run(): Implicitly marking parameter $argv as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/src/php/Phel.php on line 36
PHP Deprecated:  Gacela\Framework\Bootstrap\GacelaConfig::enableFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 190

Deprecated: Gacela\Framework\Bootstrap\GacelaConfig::enableFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 190
PHP Deprecated:  Gacela\Framework\Bootstrap\GacelaConfig::setFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 199

Deprecated: Gacela\Framework\Bootstrap\GacelaConfig::setFileCache(): Implicitly marking parameter $dir as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/vendor/gacela-project/gacela/src/Framework/Bootstrap/GacelaConfig.php on line 199
PHP Deprecated:  Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $input as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21

Deprecated: Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $input as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
PHP Deprecated:  Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $output as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21

Deprecated: Phel\Console\Infrastructure\ConsoleBootstrap::run(): Implicitly marking parameter $output as nullable is deprecated, the explicit nullable type must be used instead in ~/Builds/phel/phel-lang.git/src/php/Console/Infrastructure/ConsoleBootstrap.php on line 21
Phel v0.16.0

```

**Comment by bentxt** [comment]
> The thing is that PHP 8.4 is very fresh, and there are still some things to adapt to make it work 100% In the meanwhile, if you want to give it a try to phel, you can use PHP 8.3 which is tested and working fine.
> 
> However, I appreciate if you help me finding these "broken UX" use-cases to fix for PHP 8.4, this will definitely help us to make the upgrade faster :)

The problem is, I could not figure out how to install php 8.3 because 8.4 is automatically installed the moment I install composer.

**Comment by bentxt** [comment]
I think I was able to overwrite the automatic install and linkage of php 8.4 by composer by running

```
# on macos 
brew brew link --overwrite --force  php@8.3
```

with 8.3 the deprecation message seem to be gone indeed.

**Comment by Chemaclass** [comment]
New release with support for PHP 8.4 -> https://github.com/phel-lang/phel-lang/releases/tag/v0.16.1
Running tests with PHP 8.4 added to the CI
- [Core tests](https://github.com/phel-lang/phel-lang/actions/runs/12320235218/job/34389042821)
- [Compiler tests](https://github.com/phel-lang/phel-lang/actions/runs/12320235218/job/34389041753)

![Screenshot 2024-12-13 at 18 29 29](https://github.com/user-attachments/assets/83dca2a0-4542-4c88-8618-17cbb9441414)

Thanks @bentxt ! 🚀

**Comment by bentxt** [comment]
Indeed, it works now, thanks

```
phel-lang.git (main)> php --version
PHP 8.4.1 (cli) (built: Nov 20 2024 09:48:35) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies

phel-lang.git (main)> ./bin/phel --version
Phel v0.16.1
